# Generated by Django 3.2.5 on 2022-06-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboard',
            name='owner',
        ),
    ]
