# Generated by Django 3.1.14 on 2022-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_remove_userdashboard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
